abstract class ProfileMainState{}
class InitProfileState extends ProfileMainState{}
class GetProfileState extends ProfileMainState{}
class GetMyBookingState extends ProfileMainState{}
class UpdateMyBookingState extends ProfileMainState{}
class EmptyBookingState extends ProfileMainState{}
class TranselateState extends ProfileMainState{}
class GetImageStateScound extends ProfileMainState{}
class AddImageProfile extends ProfileMainState{}
class AddImageShopState extends ProfileMainState{}
class AddImageProtoState extends ProfileMainState{}
class GetStatusData extends ProfileMainState{}
class MyBookingManageState extends ProfileMainState{}
class GetShopData extends ProfileMainState{}
class UpdateShopData extends ProfileMainState{}
class AddServiceState extends ProfileMainState{}
class AddInfoState extends ProfileMainState{}
class TypeState extends ProfileMainState{}
class EmptyState extends ProfileMainState{}
class EmptyStatusState extends ProfileMainState{}
class ChoseState extends ProfileMainState{}
class ChoseBookingState extends ProfileMainState{}
